#!/usr/bin/env python
"""Generate the ``arasaac`` Agent Skill and the MCP recipe resources.

``scripts/prompt.md`` is the single source of truth for the transcriber rules.
Two generated targets:

- ``skills/arasaac/SKILL.md`` — the deliberately thin Agent Skill: only the
  always-needed core (language, word addressing) plus a map to the recipe
  resources, so it stays small in any Agent-Skills harness.
- ``arasaac_mcp/recipe/*.md`` — the recipe parts the ``arasaac-mcp`` server
  serves as resources (``arasaac://rules/<part>``), loaded on demand.  They
  live in the package, so an installed wheel keeps serving them.

Usage:
    python scripts/build_skill.py           # (re)write both targets
    python scripts/build_skill.py --check   # fail if the generated files are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "prompt.md"
SKILL_DIR = ROOT / "skills" / "arasaac"
RECIPE_DIR = ROOT / "arasaac_mcp" / "recipe"

SKILL_NAME = "arasaac"
SKILL_DESCRIPTION = (
    "Turn German text (a sentence, situation, rule, routine, request or a structured "
    "timetable) into an ordered ARASAAC pictogram sequence or free layout that is "
    "understandable from the pictures alone, and render it as an image. Use when the "
    "user wants a pictogram strip, AAC symbols, a visual schedule or timetable, or an "
    "easy-to-understand picture version of German text."
)

#: Which prompt.md sections go where.  Paths are relative to the repo root.
#: The skill keeps only the core; the recipe parts are served as resources by
#: the MCP server.  Section numbers are preserved so the cross-references
#: inside the text ("see §9") keep working.
LAYOUT: dict[str, list[int]] = {
    "skills/arasaac/SKILL.md": [0, 3],
    "arasaac_mcp/recipe/core.md": [0, 3],
    "arasaac_mcp/recipe/workflow.md": [4, 10, 13],
    "arasaac_mcp/recipe/design.md": [1, 2, 5, 6, 7, 8],
    "arasaac_mcp/recipe/layouts.md": [9],
    "arasaac_mcp/recipe/contract.md": [11, 12],
    "arasaac_mcp/recipe/sources.md": [14],
}

REFERENCE_MAP = """\
| Need | Resource |
| --- | --- |
| Tools, workflow, checklist | `arasaac://rules/workflow` |
| Design, reduction, icon selection, ordering | `arasaac://rules/design` |
| Layouts (strips, timetables, cards) | `arasaac://rules/layouts` |
| Output contract and worked examples | `arasaac://rules/contract` |
| Sources and further reading | `arasaac://rules/sources` |
"""

_GENERATED = "<!-- Generated by scripts/build_skill.py from scripts/prompt.md. Do not edit by hand. -->"


def parse_sections(text: str) -> tuple[str, dict[int, str]]:
    """Split ``prompt.md`` into its title and numbered ``## N.`` sections."""
    title = ""
    sections: dict[int, list[str]] = {}
    current: int | None = None
    for line in text.splitlines():
        if not title and line.startswith("# "):
            title = line[2:].strip()
            continue
        match = re.match(r"^## (\d+)\.\s", line)
        if match:
            current = int(match.group(1))
            sections[current] = [line]
            continue
        if current is not None:
            sections[current].append(line)
    return title, {number: "\n".join(lines).rstrip() for number, lines in sections.items()}


def _require(sections: dict[int, str], number: int) -> str:
    if number not in sections:
        raise SystemExit(f"scripts/prompt.md: missing section §{number}")
    return sections[number]


def build_files() -> dict[str, str]:
    title, sections = parse_sections(SOURCE.read_text(encoding="utf-8"))

    skill_parts = [
        "---",
        f"name: {SKILL_NAME}",
        f"description: {SKILL_DESCRIPTION}",
        "allowed-tools: search_pictograms view_pictogram render_pictogram_sheet render_pictogram_layout",
        "---",
        "",
        _GENERATED,
        "",
        f"# {title}",
        "",
        "This skill turns German text into ARASAAC pictograms. It is deliberately",
        "thin: the full recipe is served by the connected MCP server (the one that",
        "provides the pictogram tools) as resources — read `arasaac://rules`",
        "(everything at once) or the individual parts in the map below; the",
        "`pictogram_transcriber` prompt embeds the recipe together with the German",
        "text. Read the resources on that same server, whatever it is called in",
        "your host.",
        "",
        "## Recipe resources",
        "",
        REFERENCE_MAP.rstrip(),
        "",
    ]
    for number in LAYOUT["skills/arasaac/SKILL.md"]:
        skill_parts += [_require(sections, number), ""]

    files = {}
    skill_file = "skills/arasaac/SKILL.md"
    files[skill_file] = "\n".join(skill_parts).rstrip() + "\n"
    for relative, numbers in LAYOUT.items():
        if relative == skill_file:
            continue
        parts = [_GENERATED, "", f"# {title} — {Path(relative).stem}", ""]
        parts += [f"{_require(sections, number)}\n" for number in numbers]
        files[relative] = "\n".join(parts).rstrip() + "\n"
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if files are stale")
    args = parser.parse_args(argv)

    files = build_files()
    stale: list[str] = []
    for relative, content in files.items():
        path = ROOT / relative
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.is_file() else None
            if existing != content:
                stale.append(relative)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")

    if args.check:
        if stale:
            print("stale skill files (run scripts/build_skill.py):", file=sys.stderr)
            for relative in stale:
                print(f"  - skills/{relative}", file=sys.stderr)
            return 1
        print(f"skill files up to date ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
