#!/usr/bin/env python
"""Generate the ``arasaac`` Agent Skill from ``scripts/prompt.md``.

``scripts/prompt.md`` is the single source of truth for the transcriber rules.
This script splits it into a short, always-loaded ``SKILL.md`` plus on-demand
reference files (progressive disclosure), so the same rules can be used by any
harness that understands the Agent Skills standard (Claude, IDEs, …) without
duplicating them by hand.

Usage:
    python scripts/build_skill.py           # (re)write skills/arasaac
    python scripts/build_skill.py --check   # fail if the generated files are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "prompt.md"
SKILL_DIR = ROOT / "skills" / "arasaac"

SKILL_NAME = "arasaac"
SKILL_DESCRIPTION = (
    "Turn German text (a sentence, situation, rule, routine, request or a structured "
    "timetable) into an ordered ARASAAC pictogram sequence or free layout that is "
    "understandable from the pictures alone, and render it as an image. Use when the "
    "user wants a pictogram strip, AAC symbols, a visual schedule or timetable, or an "
    "easy-to-understand picture version of German text."
)

#: Which prompt.md sections go where.  Section numbers are preserved so the
#: cross-references inside the text ("see §2") keep working.
LAYOUT: dict[str, list[int]] = {
    "SKILL.md": [0, 3, 4, 10, 13],
    "references/design.md": [1, 2, 5, 6, 7, 8],
    "references/layouts.md": [9],
    "references/contract.md": [11, 12],
    "references/references.md": [14],
}

REFERENCE_MAP = """\
| Need | Read |
| --- | --- |
| Design, reduction, icon selection, ordering | [references/design.md](references/design.md) |
| Layouts (strips, timetables, cards) | [references/layouts.md](references/layouts.md) |
| Output contract and worked examples | [references/contract.md](references/contract.md) |
| Sources and further reading | [references/references.md](references/references.md) |
"""

_GENERATED = "<!-- Generated by scripts/build_skill.py from scripts/prompt.md. Do not edit by hand. -->"


def parse_sections(text: str) -> tuple[str, dict[int, str]]:
    """Split ``prompt.md`` into its title and numbered ``## N.`` sections."""
    title = ""
    sections: dict[int, list[str]] = {}
    current: int | None = None
    for line in text.splitlines():
        if not title and line.startswith("# "):
            title = line[2:].strip()
            continue
        match = re.match(r"^## (\d+)\.\s", line)
        if match:
            current = int(match.group(1))
            sections[current] = [line]
            continue
        if current is not None:
            sections[current].append(line)
    return title, {number: "\n".join(lines).rstrip() for number, lines in sections.items()}


def _require(sections: dict[int, str], number: int) -> str:
    if number not in sections:
        raise SystemExit(f"scripts/prompt.md: missing section §{number}")
    return sections[number]


def build_files() -> dict[str, str]:
    title, sections = parse_sections(SOURCE.read_text(encoding="utf-8"))

    skill_parts = [
        "---",
        f"name: {SKILL_NAME}",
        f"description: {SKILL_DESCRIPTION}",
        "allowed-tools: search_pictograms view_pictogram render_pictogram_sheet render_pictogram_layout",
        "---",
        "",
        _GENERATED,
        "",
        f"# {title}",
        "",
        "This skill turns German text into ARASAAC pictograms. The section numbers below",
        "match `scripts/prompt.md`; sections listed in the reference map are loaded from the",
        "`references/` directory on demand.",
        "",
        "## Reference map",
        "",
        REFERENCE_MAP.rstrip(),
        "",
    ]
    for number in LAYOUT["SKILL.md"]:
        skill_parts += [_require(sections, number), ""]

    files = {f"{SKILL_NAME}/SKILL.md": "\n".join(skill_parts).rstrip() + "\n"}
    for relative, numbers in LAYOUT.items():
        if relative == "SKILL.md":
            continue
        parts = [_GENERATED, "", f"# {title} — {Path(relative).stem}", ""]
        parts += [f"{_require(sections, number)}\n" for number in numbers]
        files[f"{SKILL_NAME}/{relative}"] = "\n".join(parts).rstrip() + "\n"
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if files are stale")
    args = parser.parse_args(argv)

    files = build_files()
    stale: list[str] = []
    for relative, content in files.items():
        path = SKILL_DIR.parent / relative
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.is_file() else None
            if existing != content:
                stale.append(relative)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")

    if args.check:
        if stale:
            print("stale skill files (run scripts/build_skill.py):", file=sys.stderr)
            for relative in stale:
                print(f"  - skills/{relative}", file=sys.stderr)
            return 1
        print(f"skill files up to date ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
